# Generated by Django 4.1.1 on 2024-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('anak_judul', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('edisi', models.IntegerField()),
                ('penerbit', models.CharField(max_length=100)),
                ('tempat_terbit', models.CharField(max_length=100)),
                ('topik', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('rating_goodreads', models.FloatField()),
            ],
        ),
    ]
