# Generated by Django 4.1.1 on 2024-01-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_alter_buku_rating_goodreads_gambarbuku'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='sinopsis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gambarbuku',
            name='gambar',
            field=models.ImageField(upload_to='static/img/covers/'),
        ),
    ]
