# Generated by Django 4.1.1 on 2024-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_alter_buku_anak_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
