# Generated by Django 4.1.1 on 2024-01-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0005_buku_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='rekomended',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
